
language: python

python:
  - "3.4"

install:
  - pip install coverage
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage tests/test_api1.py

after_success:
  - coverage report
  - coveralls
   #uploads reports to  coveralls.io