
language: python

python:
  - "3.4"

install:
  - pip install coverage
  - pip install -r requirements.txt

script:
  - python test_api1.py

after_success:
  - coverage report
   #uploads reports to  coveralls.io