
language: python

python:
  - "3.4"


install:
  - pip install coverage
  - pip install coveralls
  - pip install nose-cov
  - pip install -r requirements.txt


services:
  - postgresql



before_script:
  - psql -c "CREATE DATABASE testmyconnect;" -U postgres

env:
  - DATABASE_URL=postgresql://@localhost/testmyconnect SECRET_KEY=this-should-be-secret APP_SETTINGS=config.TestingConfig



script:
<<<<<<< HEAD
  - pytest --cov api/v1/tests/
=======
  - nosetests --with-cov --cov tests/


>>>>>>> challenge3

after_success:
  - coverage report
  - coveralls
   #uploads reports to  coveralls.io
