
language: python

python:
  - "3.4"


install:
  - pip install coverage
  - pip install coveralls
  - pip install pytest-cov
  - pip install -r requirements.txt


services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE testmyconnect;" -U postgres

script:
  - python api/v1/tests/test_api1.py
  - python api/v2/tests/test_auth.py
  - python api/v2/tests/test_api2.py



after_success:
  - coverage report
  - coveralls
   #uploads reports to  coveralls.io
