
language: python

python:
  - "3.4"


install:
  - pip install coverage
  - pip install coveralls
  - pip install pytest-cov
  - pip install -r requirements.txt


services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE testmyconnect;" -U postgres

script:
  - python -m pytest --cov api/v1/tests/
  - python -m pytest --cov api/v2/tests/



after_success:
  - coverage report
  - coveralls
   #uploads reports to  coveralls.io
