"""empty message

Revision ID: 740cb618cb1c
Revises: a0a99910b7a4
Create Date: 2018-04-22 20:12:41.630713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740cb618cb1c'
down_revision = 'a0a99910b7a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_on')
    # ### end Alembic commands ###
