"""empty message

Revision ID: 898b14dcaadc
Revises: c7d11f32bc90
Create Date: 2018-03-21 10:43:13.118476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898b14dcaadc'
down_revision = 'c7d11f32bc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
