"""empty message

Revision ID: a0a99910b7a4
Revises: 564f21743f99
Create Date: 2018-04-14 21:24:51.509856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a99910b7a4'
down_revision = '564f21743f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reviewed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'reviewed_on')
    # ### end Alembic commands ###
