"""empty message

Revision ID: 564f21743f99
Revises: 898b14dcaadc
Create Date: 2018-03-24 22:42:46.687116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564f21743f99'
down_revision = '898b14dcaadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('category', sa.String(length=200), nullable=True))
    op.add_column('businesses', sa.Column('location', sa.String(length=100), nullable=True))
    op.drop_column('businesses', 'business_category')
    op.drop_column('businesses', 'business_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('business_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('business_category', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'location')
    op.drop_column('businesses', 'category')
    # ### end Alembic commands ###
